kind = "mobile"
previewPath = "/menu-mobile/"
title = "MenuClick Mobile"
version = "1.0.0"
id = "artifacts/menu-mobile"
router = "expo-domain"

[[services]]
name = "expo"
ensurePreviewReachable = "/status"
paths = [ "/menu-mobile/" ]
localPort = 19236

[services.development]
run = "pnpm --filter @workspace/menu-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/menu-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/menu-mobile", "run", "serve" ]

[services.env]
PORT = "19236"
BASE_PATH = "/menu-mobile/"
